baseURL = "https://ntutiae.github.io/"
languageCode = "zh"
title = "北科大智慧自動化工程科"
hasCJKLanguage = true

[[menu.main]]
    name = "智慧自動化工程科"
    weight = -1
    url = "/"

[[menu.main]]
    name = "關於本科"
    weight = 1
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "師資介紹"
    parent = "about"
    url = "/about/teachers/"

[[menu.main]]
    name = "職涯發展"
    parent = "about"
    url = "/about/career"

[[menu.main]]
    name = "活動總覽"
    weight = 10
    url = "/events/"

[[menu.main]]
    name = "學生成果"
    weight = 20
    identifier = "works"

[[menu.main]]
    name = "學習心得影片"
    parent = "works"
    url = "/reflections/"

[[menu.main]]
    name = "學生專題"
    parent = "works"
    url = "/projects/"

[[menu.main]]
    name = "常見問題"
    weight = 30
    url = "/faq/"

[params]
    timeFormat = "Jan. 2. 2006"
